pnp_solver:
  ros__parameters:
    calibrate_default_points:
      farCam:
        point1:
          x: 0.5139
          y: 0.3194
        point2:
          x: 0.4931
          y: 0.5593
        point3:
          x: 0.8285
          y: 0.5509
        point4:
          x: 0.6313
          y: 0.3231
      closeCam:
        point1:
          x: 0.3403
          y: 0.3778
        point2:
          x: 0.3063
          y: 0.7009
        point3:
          x: 0.5701
          y: 0.6250
        point4:
          x: 0.4632
          y: 0.3750

#  far(1080, 1440)
#far count --0-- : ( 740 , 345 ) (0.5139, 0.3194)
#far count --1-- : ( 710 , 604 ) (0.4931, 0.5593)
#far count --4-- : ( 1193 , 595 ) (0.8285, 0.5509)
#far count --3-- : ( 909 , 349 ) (0.6313, 0.3231)
#
#  close
#close count --0-- : ( 490 , 408 ) (0.3403, 0.3778)
#close count --1-- : ( 441 , 757 ) (0.3063, 0.7009)
#close count --2-- : ( 821 , 675 ) (0.5701, 0.6250)
#close count --3-- : ( 667 , 405 ) (0.4632, 0.375)