pnp_solver:
  ros__parameters:
    calibrate_default_points:
      farCam:
        image_points:
          point1:
            x: 0.33958
            y: 0.44583
          point2:
            x: 0.0354167
            y: 0.943
          point3:
            x: 0.59
            y: 0.9222
          point4:
            x: 0.9443
            y: 0.589
          point5:
            x: 0.8474
            y: 0.418
        world_points:
          point1:
            x: 9700.0
            y: 14000.0
            z: 0.0
          point2:
            x: 900.0
            y: 14000.0
            z: 0.0
          point3:
            x: 900.0
            y: 11000.0
            z: 0.0
          point4:
            x: 5000.0
            y: 8200.0
            z: 0.0
          point5:
            x: 9700.0
            y: 8200.0
            z: 0.0

      closeCam:
        image_points:
          point1:
            x: 0.263
            y: 0.1264
          point2:
            x: 0.329
            y: 0.2583
          point3:
            x: 0.0382
            y: 0.54
          point4:
            x: 0.8186
            y: 0.193
          point5:
            x: 0.77
            y: 0.122
        world_points:
          point1:
            x: 9700.0
            y: 8200.0
            z: 0.0
          point2:
            x: 5000.0
            y: 8200.0
            z: 0.0
          point3:
            x: 900.0
            y: 11000.0
            z: 0.0
          point4:
            x: 6600.0
            y: 0.0
            z: 0.0
          point5:
            x: 8400.0
            y: 0.0
            z: 0.0

# point1:
#             x: 720.0
#             y: 7400.0
#             z: 1470.0
#           point2:
#             x: 1700.0
#             y: 6740.0
#             z: 200.0
#           point3:
#             x: 3760.0
#             y: 6740.0
#             z: 400.0
#           point4:
#             x: 3660.0
#             y: 4700.0
#             z: 0.0

