pnp_solver:
  ros__parameters:
    calibrate_default_points:
      farCam:
        image_points:
          point1:
            x: 0.24045
            y: 0.17778
          point2:
            x: 0.065972
            y: 0.490275
          point3:
            x: 0.54167
            y: 0.302775
          point4:
            x: 0.4991
            y: 0.21806
          point5:
            x: 0.85156
            y: 0.216667
        world_points:
          point1:
            x: 9700.0
            y: 14000.0
            z: 0.0
          point2:
            x: 0.0
            y: 14000.0
            z: 0.0
          point3:
            x: 5000.0
            y: 8200.0
            z: 0.0
          point4:
            x: 9700.0
            y: 8200.0
            z: 0.0
          point5:
            x: 8400.0
            y: 0.0
            z: 0.0

      closeCam:
        image_points:
          point1:
            x: 0.17361
            y: 0.508333
          point2:
            x: 0.099826
            y: 0.6097
          point3:
            x: 0.6979167
            y: 0.7097
          point4:
            x: 0.6111
            y: 0.55
          point5:
            x: 0.5764
            y: 0.45556
        world_points:
          point1:
            x: 15000.0
            y: 14000.0
            z: 0.0
          point2:
            x: 9700.0
            y: 14000.0
            z: 0.0
          point3:
            x: 5000.0
            y: 8200.0
            z: 0.0
          point4:
            x: 9700.0
            y: 8200.0
            z: 0.0
          point5:
            x: 15000.0
            y: 8200.0
            z: 0.0

# point1:
#             x: 720.0
#             y: 7400.0
#             z: 1470.0
#           point2:
#             x: 1700.0
#             y: 6740.0
#             z: 200.0
#           point3:
#             x: 3760.0
#             y: 6740.0
#             z: 400.0
#           point4:
#             x: 3660.0
#             y: 4700.0
#             z: 0.0

