pnp_solver:
  ros__parameters:
    calibrate_default_points:
      farCam:
        point1:
          x: 0.247
          y: 0.070
        point2:
          x: 0.541
          y: 0.411
        point3:
          x: 0.632
          y: 0.411
        point4:
          x: 0.614
          y: 0.016
      closeCam:
        point1:
          x: 0.500
          y: 0.073
        point2:
          x: 0.448
          y: 0.281
        point3:
          x: 0.493
          y: 0.281
        point4:
          x: 0.843
          y: 0.189