sensor_far:
  bayer_camera_driver:
    ros__parameters:
      camera_name: camera_far
      camera_height: 1080
      camera_width: 1440
      camera_exp: 2500.0
      camera_gain: 23.98
      camera_auto_exp: 0
      camera_auto_maxexp: 4500.0
      camera_auto_minexp: 100.0
      camera_auto_gain: 0
      camera_auto_maxgain: 17.0
      camera_auto_mingain: 0.0
      camera_auto_whitebalance: 1

sensor_close:
  bayer_camera_driver:
    ros__parameters:
      camera_name: camera_close
      camera_height: 1080
      camera_width: 1440
      camera_exp: 4500.0
      camera_gain: 22.05
      camera_auto_exp: 0
      camera_auto_maxexp: 4500.0
      camera_auto_minexp: 100.0
      camera_auto_gain: 1
      camera_auto_maxgain: 17.0
      camera_auto_mingain: 0.0
      camera_auto_whitebalance: 1
