small_map:
  ros__parameters:
    small_map_params:
      small_map_shift_X: 0
      small_map_shift_Y: 0
      field_width: 15.0
      field_height: 28.0
      imgCols: 1920.0
      imgRows: 1200.0
      dist_threshold: 5.0
      center_far:
        x: 5.0
        y: 8.0
      center_far:
        x: 22.0
        y: 3.0

    battle_state:
      our_color: "blue"
      fps_mode: 0
