pnp_solver:
  ros__parameters:

    sensor_far:
      deviceID: 0
      exp_time: 25000
      fps: 400
      camera_name: "changjiao"
      camera_matrix:
        zerozero: 1890.751574
        zerotwo: 645.397327
        oneone: 1883.882471
        onetwo: 529.402852
        twotwo: 1.0
      distortion_coefficient:
        zero: -0.110864
        one: 0.067284
        two: -0.000661
        three: 0.001910
        four: 0.000000
      uni_matrix:
        zerozero: 0.161993
        zeroone: -0.985181
        zerotwo: 0.0563563
        zerothree: 0.124679
        onezero: 0.06279
        oneone: -0.0467041
        onetwo: -0.996933
        onethree: -0.00135317
        twozero: 0.984792
        twoone: 0.165035
        twotwo: 0.0542938
        twothree: 0.118454
      point1:
        x: 2461.0
        y: 16706.0
        z: 1581.0
      point2:
        x: 6321.0
        y: 8805.0
        z: 615.0
      point3:
        x: 6981.0
        y: 8805.0
        z: 615.0
      point4:
        x: 7500.0
        y: 26302.0
        z: 1118.0

    sensor_close:
      deviceID: 1
      exp_time: 28000
      camera_name: guangjiao
      camera_matrix:
        zerozero: 1854.708250
        zerotwo: 661.706219
        oneone: 1847.979719
        onetwo: 512.214798
        twotwo: 1.0
      distortion_coefficient:
        zero: -0.089024
        one: 0.390152
        two: 0.000047
        three: 0.002143
        four: 0.000000
      uni_matrix:
        zerozero: -0.339105
        zeroone: -0.935727
        zerotwo: -0.0970715
        zerothree: -0.118438
        onezero: 0.0747155
        oneone: 0.076071
        onetwo: -0.994299
        onethree: 0.0127523
        twozero: 0.937777
        twoone: -0.344425
        twotwo: 0.0441172
        twothree: -0.0207261
      point1:
        x: 7500.0
        y: 26302.0
        z: 1118.0
      point2:
        x: 6321.0
        y: 8805.0
        z: 615.0
      point3:
        x: 6981.0
        y: 8805.0
        z: 615.0
      point4:
        x: 12539.0
        y: 11294.0
        z: 1581.0

    length_of_cloud_queue: 10
    image_width: 1280
    image_height: 1024