small_map:
  ros__parameters:
    small_map_params:
      small_map_shift_X: 0
      small_map_shift_Y: 0
      field_width: 14.0
      field_height: 15.0
      imgCols: 1920.0
      imgRows: 1200.0
      dist_threshold: 2.0

    battle_state:
      our_color: "red"
      fps_mode: 0
