pnp_solver:
  ros__parameters:
    world_length: 10
    image_length: 5
    calibrate_default_points:
      closeCam:
        image_points:
          point1:
            id: 0
            x: 0.2639
            y: 0.172225
          point2:
            id: 1
            x: 0.020833
            y: 0.552775
          point3:
            id: 2
            x: 0.54167
            y: 0.3014
          point4:
            id: 3
            x: 0.4974
            y: 0.21667
          point5:
            id: 4
            x: 0.8498
            y: 0.2125

      farCam:
        image_points:
          point1:
            id: 5
            x: 0.17448
            y: 0.50694
          point2:
            id: 6
            x: 0.1041667
            y: 0.6097
          point3:
            id: 7
            x: 0.6918
            y: 0.7125
          point4:
            id: 8
            x: 0.6085
            y: 0.55139
          point5:
            id: 9
            x: 0.5703
            y: 0.4597

      world_points:
        x: [9700.0, 0.0, 5000.0, 9700.0, 8400.0, 15000.0, 9700.0, 5000.0, 9700.0, 15000.0]
        y: [14000.0, 14000.0, 8200.0, 8200.0, 0.0, 14000.0, 14000.0, 8200.0, 8200.0, 8200.0]
        z: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
