small_map:
  ros__parameters:
    length: 20
    x: []
    y: []
    z: []


    p0:
      x:
      y:
    p1:
      x:
      y:
    p2:
      x:
      y:
    p3:
      x:
      y:
    p4:
      x:
      y:
    p5:
      x:
      y:
    p6:
      x:
      y:
    p7:
      x:
      y:
    p8:
      x:
      y:
    p9:
      x:
      y:
    p10:
      x:
      y:
    p11:
      x:
      y:
    p12:
      x:
      y:
    p13:
      x:
      y:
    p14:
      x:
      y:
    p15:
      x:
      y:
    p16:
      x:
      y:
    p17:
      x:
      y:
    p18:
      x:
      y:
    p19:
      x:
      y:
    p20:
      x:
      y:
1.  5166.31,   10567.47,   535.0
2.  12082.16,  13859.49,   735.0
3.  8918.32,   9340.3,     735.0
4.  8918.32,   9340.3,     0.0
5. 
6. 
7. 
8. 
9.  14773.98, 3537.21, 94.61
10. 14883.59, 2457.99,   285.0
11. 16175.49, 3932.90,   735.0
12. 16234.72, 1140.49,   735.0
13. 20844.48, 1140.0,   535.0
14. 21911.15, 2739.04, 560.0
15. 23149.93, 4432.53,   535.0
16. 
17. 
18. 6732.47,   7520.0      1.90
19. 
20. 
